In [1]:
import numpy as np

# Создание массива 3x3 с числами от 1 до 9
arr = np.arange(1, 10).reshape(3, 3)
print("Исходный массив:")
print(arr)

# Умножаем все элементы на 2
arr = arr * 2
print("Умноженный на 2:")
print(arr)

# Заменяем элементы больше 10 на 0
arr[arr > 10] = 0
print("Элементы больше 10 заменены на 0:")
print(arr)

Исходный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Умноженный на 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Элементы больше 10 заменены на 0:
[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]
