In [1]:
import numpy as np

# Создание массива из 20 случайных целых чисел от 1 до 100
arr = np.random.randint(1, 101, 20)
print("Исходный массив:")
print(arr)

# Находим элементы, которые делятся на 5
mask = arr % 5 == 0
print("Элементы, делящиеся на 5:")
print(arr[mask])

# Заменяем найденные элементы на -1
arr[mask] = -1
print("Обновленный массив:")
print(arr)

Исходный массив:
[23  2 65 67 33 31 72 66 44 26 10 78 71 77 78 90 29 19 38 34]
Элементы, делящиеся на 5:
[65 10 90]
Обновленный массив:
[23  2 -1 67 33 31 72 66 44 26 -1 78 71 77 78 -1 29 19 38 34]
