In [1]:
import numpy as np

# Единичная матрица 4x4
I = np.eye(4)
print("Единичная матрица:\n", I)

# Диагональная матрица 4x4 с [5, 10, 15, 20]
diag = np.diag([5, 10, 15, 20])
print("Диагональная матрица:\n", diag)

# Суммы элементов
sum_I = I.sum()
sum_diag = diag.sum()
print("Сумма всех элементов единичной матрицы:", sum_I)
print("Сумма всех элементов диагональной матрицы:", sum_diag)

Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма всех элементов единичной матрицы: 4.0
Сумма всех элементов диагональной матрицы: 50
