In [1]:
import numpy as np

# Две квадратные матрицы 3x3 со случайными числами от 1 до 20
A = np.random.randint(1, 21, (3, 3))
B = np.random.randint(1, 21, (3, 3))
print("Матрица A:\n", A)
print("Матрица B:\n", B)

# Сумма
print("Сумма матриц:\n", A + B)
# Разность
print("Разность матриц:\n", A - B)
# Поэлементное произведение
print("Поэлементное произведение:\n", A * B)

Матрица A:
 [[16 14 19]
 [ 5  1 14]
 [ 6  2 14]]
Матрица B:
 [[18 15  2]
 [12  2 20]
 [ 7 20  4]]
Сумма матриц:
 [[34 29 21]
 [17  3 34]
 [13 22 18]]
Разность матриц:
 [[ -2  -1  17]
 [ -7  -1  -6]
 [ -1 -18  10]]
Поэлементное произведение:
 [[288 210  38]
 [ 60   2 280]
 [ 42  40  56]]
