In [1]:
import numpy as np

# Первая матрица 2x3
A = np.random.randint(1, 11, (2, 3))
# Вторая матрица 3x2
B = np.random.randint(1, 11, (3, 2))
print("Матрица A:\n", A)
print("Матрица B:\n", B)

# Матричное умножение
product = A @ B  # или np.dot(A, B)
print("Результат умножения:\n", product)

Матрица A:
 [[8 6 8]
 [4 7 9]]
Матрица B:
 [[9 2]
 [7 3]
 [7 8]]
Результат умножения:
 [[170  98]
 [148 101]]
