In [1]:
import numpy as np

# Случайная квадратная матрица 3x3
A = np.random.randint(1, 11, (3, 3))
print("Матрица A:\n", A)

# Определитель
det = np.linalg.det(A)
print("Определитель:", det)

# Обратная матрица (если существует)
if np.isclose(det, 0):
    print("Матрица вырождена, обратной не существует.")
else:
    inv = np.linalg.inv(A)
    print("Обратная матрица:\n", inv)

Матрица A:
 [[7 8 7]
 [7 1 6]
 [3 8 2]]
Определитель: 80.99999999999996
Обратная матрица:
 [[-0.56790123  0.49382716  0.50617284]
 [ 0.04938272 -0.08641975  0.08641975]
 [ 0.65432099 -0.39506173 -0.60493827]]
