In [1]:
import numpy as np

# Матрица 4x4 из случайных чисел от 1 до 50
A = np.random.randint(1, 51, (4, 4))
print("Исходная матрица:\n", A)

# Транспонирование
AT = A.T
print("Транспонированная матрица:\n", AT)

# След
trace = np.trace(A)
print("След матрицы:", trace)

Исходная матрица:
 [[36 27 24 16]
 [20  2 10 13]
 [39  2 28 42]
 [12 40 24 38]]
Транспонированная матрица:
 [[36 20 39 12]
 [27  2  2 40]
 [24 10 28 24]
 [16 13 42 38]]
След матрицы: 104
